export const KEYWORDS_GET_KEYWORDS_GET = 'KEYWORDS_GET_KEYWORDS_GET';
export const KEYWORDS_GET_KEYWORDS_GET_INIT = 'KEYWORDS_GET_KEYWORDS_GET_INIT';
export const KEYWORDS_GET_KEYWORDS_GET_SUCCESS = 'KEYWORDS_GET_KEYWORDS_GET_SUCCESS';
export const KEYWORDS_GET_KEYWORDS_GET_FAILURE = 'KEYWORDS_GET_KEYWORDS_GET_FAILURE';

export const KEYWORDS_ADD_KEYWORD_POST = 'KEYWORDS_ADD_KEYWORD_POST';
export const KEYWORDS_ADD_KEYWORD_POST_INIT = 'KEYWORDS_ADD_KEYWORD_POST_INIT';
export const KEYWORDS_ADD_KEYWORD_POST_SUCCESS = 'KEYWORDS_ADD_KEYWORD_POST_SUCCESS';
export const KEYWORDS_ADD_KEYWORD_POST_FAILURE = 'KEYWORDS_ADD_KEYWORD_POST_FAILURE';

export const KEYWORDS_DELETE_KEYWORD_DELETE = 'KEYWORDS_DELETE_KEYWORD_DELETE';
export const KEYWORDS_DELETE_KEYWORD_DELETE_INIT = 'KEYWORDS_DELETE_KEYWORD_DELETE_INIT';
export const KEYWORDS_DELETE_KEYWORD_DELETE_SUCCESS = 'KEYWORDS_DELETE_KEYWORD_DELETE_SUCCESS';
export const KEYWORDS_DELETE_KEYWORD_DELETE_FAILURE = 'KEYWORDS_DELETE_KEYWORD_DELETE_FAILURE';