export const USER_ADD_FIELDOFSTUDY_POST = 'USER_ADD_FIELDOFSTUDY_POST';
export const USER_ADD_FIELDOFSTUDY_POST_SUCCESS = 'USER_ADD_FIELDOFSTUDY_POST_SUCCESS';
export const USER_ADD_FIELDOFSTUDY_POST_FAILURE = 'USER_ADD_FIELDOFSTUDY_POST_FAILURE';
export const USER_ADD_FIELDOFSTUDY_POST_INIT = 'USER_ADD_FIELDOFSTUDY_POST_INIT';

export const USER_GET_FIELDSOFSTUDY_GET = 'USER_GET_FIELDSOFSTUDY_GET';
export const USER_GET_FIELDSOFSTUDY_GET_SUCCESS = 'USER_GET_FIELDSOFSTUDY_GET_SUCCESS';
export const USER_GET_FIELDSOFSTUDY_GET_FAILURE = 'USER_GET_FIELDSOFSTUDY_GET_FAILURE';
export const USER_GET_FIELDSOFSTUDY_GET_INIT = 'USER_GET_FIELDSOFSTUDY_GET_INIT';